trigger: none

name: '$(GitVersion.MajorMinorPatch)'

pool:
  vmImage: 'windows-latest'

#variables:
#  vstsFeed: 'af9a044c-47df-4b2e-bae8-1ea6da771ce7'

steps:
- task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  
- task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: 'pipelines/GitVersion.yml'

- task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: '$(Build.Repository.LocalPath)/src/**/*.csproj'

- task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'packages'
      publishLocation: 'Container'

#- task: DotNetCoreCLI@2
#  displayName: 'DbScaffolding and DbScaffolding.Identity dotnet push'
#  inputs:
#    command: push
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '$(vstsFeed)'
